modLoader="javafml"
loaderVersion="[43,)"
license="Custom license"

[[mods]]
modId="pureamethysttools"
version="1.0.0"
displayName="Pure Amethyst Tools"
credits="Made by purejosh"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pure-amethyst-tools-fabric-forge"
logoFile="logo.png"
authors="purejosh"
description="A unique take on amethyst armor and tools, that just may fit your vibe."

[[dependencies.pureamethysttools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




